replicaCount: 3

image:
  tag: ""

ingress:
  hosts:
    - host: ${{values.app_name}}-prod.test.com
      paths:
        - path: /
          pathType: Prefix

resources:
  requests:
    cpu: 60m
    memory: 60M
