apiVersion: v1
kind: Namespace
metadata:
  name: ${{values.app_name}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: arc-runner-reader
  namespace: ${{values.app_name}}
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: arc-runner-reader
  namespace: ${{values.app_name}}
subjects:
  - kind: ServiceAccount
    name: ${{values.app_name}}-runner
    namespace: ${{values.app_name}}
roleRef:
  kind: Role
  name: arc-runner-reader
  apiGroup: rbac.authorization.k8s.io
